import { Card } from "@/components/ui/Card";
import { Container } from "@/components/ui/Container";
import { SectionHeading } from "@/components/ui/SectionHeading";
import type { SeoPage } from "@/lib/seo-pages";
import { absoluteUrl, site } from "@/lib/site";

export function NameLandingPage({ page, relatedPages }: { page: SeoPage; relatedPages: SeoPage[] }) {
  const faq = [[`How do I choose a good name from these ${page.eyebrow.toLowerCase()}?`, "Pick a name you enjoy saying, that is easy to call, and that suits the personality you see every day. Try your favorites out loud with the people who share life with your pet."], ["Can I get more personalized ideas?", "Yes. Our free name generator uses the pet details and story you share to suggest six fresh names, each with a short meaning."]];
  const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: site.url }, { "@type": "ListItem", position: 2, name: page.title, item: absoluteUrl(`/${page.slug}`) }] }, { "@type": "Article", headline: page.title, description: page.description, mainEntityOfPage: absoluteUrl(`/${page.slug}`), author: { "@type": "Organization", name: site.name }, publisher: { "@type": "Organization", name: site.name } }, { "@type": "FAQPage", mainEntity: faq.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }] };
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <header className="topnav"><Container className="nav-inner"><a className="brand" href="/"><span className="brand-mark" />Pet Name Generator</a><nav aria-label="Primary navigation"><a href="/#generator">Find a name</a><a href="/dog-names">Dog names</a><a href="/cat-names">Cat names</a><a className="nav-info-link" href="/about">About</a><a className="nav-info-link" href="/contact">Contact</a></nav></Container></header>
    <main>
      <section className="seo-hero"><Container><p className="eyebrow">{page.eyebrow}</p><h1>{page.title}</h1><p className="lead">{page.intro}</p><a className="button button--primary" href="/#generator">Find a personal pet name</a></Container></section>
      <section className="section seo-examples"><Container><SectionHeading eyebrow="START HERE" title="A few names to spark the feeling." lead="Use these as gentle inspiration—your pet's story is what makes a name memorable." /><div className="seo-name-grid">{page.examples.map((name) => <Card className="seo-name-card" key={name}><strong>{name}</strong><span>A warm name idea to explore</span></Card>)}</div></Container></section>
      <section className="section seo-tips"><Container className="content-grid"><div><p className="eyebrow">HOW TO CHOOSE</p><h2>A name your pet and family can grow into.</h2></div><div className="info-list">{page.tips.map((tip, index) => <article className="info-row" key={tip}><span>0{index + 1}</span><div><strong>{tip}</strong><p>Keep the names that make you smile; the best one often feels natural from the first call.</p></div></article>)}</div></Container></section>
      <section className="section seo-related"><Container><SectionHeading eyebrow="KEEP EXPLORING" title="More pet name ideas to love." /><nav className="seo-link-grid" aria-label="Related pet naming pages">{relatedPages.map((related) => <a key={related.slug} href={`/${related.slug}`}><strong>{related.title.replace(": Find a Meaningful Name for Your Pet", "")}</strong><span>Explore ideas and inspiration</span></a>)}</nav></Container></section>
      <section className="section faq"><Container><div className="faq-title"><p className="eyebrow">QUESTIONS, ANSWERED</p><h2>Finding the right name should feel joyful.</h2></div><div className="faq-list">{faq.map(([question, answer], index) => <details key={question} open={index === 0}><summary>{question}</summary><p>{answer}</p></details>)}</div></Container></section>
      <section className="section cta"><Container><h2>There is a name waiting in your story together.</h2><p className="lead">Tell us a little about your companion and discover six names with meaning.</p><a className="button button--primary" href="/#generator">Find pet names</a></Container></section>
    </main>
    <footer><Container className="footer-row"><div className="footer-brand"><a href="/" aria-label="PetzName home">petzname.com</a><span>Thoughtful names for every kind of companion.</span></div><nav className="footer-nav" aria-label="PetzName information"><a href="/about"><strong>About</strong><small>Our story and values</small></a><a href="/contact"><strong>Contact</strong><small>Feedback and support</small></a><a href="/privacy"><strong>Privacy</strong><small>How information is handled</small></a><a href="/terms"><strong>Terms</strong><small>Service guidelines</small></a></nav></Container></footer>
  </>;
}
